"use client";

import { Bot, Check, Copy, ExternalLink, FileJson } from "lucide-react";
import { useMemo, useState } from "react";

import {
  buildAiExamPrompt,
  generateTemplateExam,
  stringifyTemplateExam,
  type TemplateTypeMinimums,
  type TemplateTypeSelection,
} from "@/lib/template-generator";

import { Button } from "./Button";
import { Checkbox } from "./checkbox";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "./dialog";
import { Input } from "./input";
import { Label } from "./label";
import { QuestionTypeRules } from "./template-generator/QuestionTypeRules";
import { Textarea } from "./textarea";

interface TemplateGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function TemplateGeneratorModal({
  isOpen,
  onClose,
}: TemplateGeneratorModalProps) {
  const [selected, setSelected] = useState<Set<TemplateTypeSelection>>(
    new Set(["true_false", "multiple_choice"]),
  );
  const [aiDecidesTypes, setAiDecidesTypes] = useState(true);
  const [aiDecidesCounts, setAiDecidesCounts] = useState(true);
  const [passingScoreInput, setPassingScoreInput] = useState("70");
  const [requireSources, setRequireSources] = useState(true);
  const [topicContext, setTopicContext] = useState("");
  const [minimumPerTypeInput, setMinimumPerTypeInput] = useState<
    Record<TemplateTypeSelection, string>
  >({
    true_false: "0",
    multiple_choice: "0",
    identification_no_choices: "0",
    identification_with_choices: "0",
    matching: "0",
    enumeration: "0",
  });
  const [feedback, setFeedback] = useState<string | null>(null);
  const [jsonCopied, setJsonCopied] = useState(false);
  const [promptCopied, setPromptCopied] = useState(false);

  const selectedArray = useMemo(() => Array.from(selected), [selected]);

  const clampInt = (
    raw: string,
    min: number,
    max: number,
    fallback: number,
  ) => {
    const parsed = Number.parseInt(raw, 10);
    if (!Number.isFinite(parsed)) return fallback;
    return Math.max(min, Math.min(max, parsed));
  };

  const passingScore = clampInt(passingScoreInput, 0, 100, 70);

  const isTypeEnabled = (type: TemplateTypeSelection) => selected.has(type);

  const setTypeEnabled = (type: TemplateTypeSelection, enabled: boolean) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (enabled) next.add(type);
      else next.delete(type);
      return next;
    });

    if (!enabled) {
      setMinimumPerTypeInput((prev) => ({ ...prev, [type]: "0" }));
      return;
    }

    if (!aiDecidesCounts) {
      setMinimumPerTypeInput((prev) => {
        const existing = Number.parseInt(prev[type], 10);
        return {
          ...prev,
          [type]: Number.isFinite(existing) && existing > 0 ? prev[type] : "1",
        };
      });
    }
  };

  const minimumPerType: TemplateTypeMinimums = {
    true_false: clampInt(minimumPerTypeInput.true_false, 0, 200, 0),
    multiple_choice: clampInt(minimumPerTypeInput.multiple_choice, 0, 200, 0),
    identification_no_choices: clampInt(
      minimumPerTypeInput.identification_no_choices,
      0,
      200,
      0,
    ),
    identification_with_choices: clampInt(
      minimumPerTypeInput.identification_with_choices,
      0,
      200,
      0,
    ),
    matching: clampInt(minimumPerTypeInput.matching, 0, 200, 0),
    enumeration: clampInt(minimumPerTypeInput.enumeration, 0, 200, 0),
  };

  const generateExam = () =>
    generateTemplateExam(
      selectedArray,
      {
        title: "Mockly AI Exam",
        description: "Exam generated by AI Exam Prompt Builder.",
        passingScore,
        subject: "General",
      },
      { aiDecidesQuestionTypesAndCounts: aiDecidesTypes && aiDecidesCounts },
    );

  const copyJson = async () => {
    if (!aiDecidesTypes && selected.size === 0) {
      setFeedback("Select at least one question type.");
      return;
    }

    await navigator.clipboard.writeText(stringifyTemplateExam(generateExam()));
    setJsonCopied(true);
    setFeedback(null);
    window.setTimeout(() => setJsonCopied(false), 1800);
  };

  const copyAiPrompt = async () => {
    if (!aiDecidesTypes && selected.size === 0) {
      setFeedback("Select at least one question type.");
      return;
    }

    const prompt = buildAiExamPrompt(generateExam(), {
      requireSources,
      allowNonJsonInput: true,
      topicContext,
      minQuestionCountPerType: minimumPerType,
      aiDecidesTypes,
      aiDecidesCounts,
    });
    await navigator.clipboard.writeText(prompt);
    setPromptCopied(true);
    setFeedback(null);
    window.setTimeout(() => setPromptCopied(false), 1800);
  };

  return (
    <Dialog
      open={isOpen}
      onOpenChange={(open) => {
        if (!open) onClose();
      }}
    >
      <DialogContent className="flex max-h-[92vh] w-full max-w-[calc(100%-1.25rem)] flex-col gap-0 overflow-hidden p-0 sm:max-w-3xl lg:max-w-4xl">
        <DialogHeader className="flex-row items-center gap-2 border-b border-border px-4 py-4 sm:px-6">
          <FileJson className="h-5 w-5 text-primary" />
          <DialogTitle>AI Exam Prompt Builder</DialogTitle>
        </DialogHeader>

        <div className="space-y-5 overflow-y-auto px-4 py-5 sm:px-6">
          <div className="rounded-lg border border-emerald-200 bg-emerald-50/60 p-3 text-sm text-emerald-900 dark:border-emerald-900/60 dark:bg-emerald-950/30 dark:text-emerald-100">
            <p className="font-medium">Quick flow</p>
            <p className="mt-1 text-xs text-emerald-800/90 dark:text-emerald-200/90">
              Copy AI prompt, paste into ChatGPT/Claude/Gemini with your
              sources, then paste the returned JSON in Import Exams.
            </p>

            <div className="mt-3 flex flex-wrap gap-2 text-xs">
              <a
                href="https://chatgpt.com"
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1 rounded-md border border-emerald-300/70 bg-white/70 px-2 py-1 text-emerald-900 hover:bg-white dark:border-emerald-800 dark:bg-slate-900/70 dark:text-emerald-200"
              >
                <span className="inline-flex h-4 w-4 items-center justify-center rounded-full bg-emerald-600 text-[10px] font-semibold text-white">
                  G
                </span>
                ChatGPT
                <ExternalLink className="h-3 w-3" />
              </a>
              <a
                href="https://claude.ai"
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1 rounded-md border border-emerald-300/70 bg-white/70 px-2 py-1 text-emerald-900 hover:bg-white dark:border-emerald-800 dark:bg-slate-900/70 dark:text-emerald-200"
              >
                <span className="inline-flex h-4 w-4 items-center justify-center rounded-full bg-emerald-600 text-[10px] font-semibold text-white">
                  C
                </span>
                Claude
                <ExternalLink className="h-3 w-3" />
              </a>
              <a
                href="https://gemini.google.com"
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1 rounded-md border border-emerald-300/70 bg-white/70 px-2 py-1 text-emerald-900 hover:bg-white dark:border-emerald-800 dark:bg-slate-900/70 dark:text-emerald-200"
              >
                <span className="inline-flex h-4 w-4 items-center justify-center rounded-full bg-emerald-600 text-[10px] font-semibold text-white">
                  M
                </span>
                Gemini
                <ExternalLink className="h-3 w-3" />
              </a>
            </div>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label htmlFor="tpl-pass">Passing Score (%)</Label>
              <Input
                id="tpl-pass"
                type="number"
                min={0}
                max={100}
                value={passingScoreInput}
                onChange={(e) => setPassingScoreInput(e.target.value)}
                onBlur={() => setPassingScoreInput(String(passingScore))}
              />
            </div>
          </div>

          <div className="flex items-center gap-3 rounded-lg border border-border px-3 py-2">
            <Checkbox
              id="ai-decides-types"
              checked={aiDecidesTypes}
              onCheckedChange={(v) => setAiDecidesTypes(!!v)}
            />
            <Label
              htmlFor="ai-decides-types"
              className="cursor-pointer font-normal"
            >
              Let AI decide question types
            </Label>
          </div>

          <div className="flex items-center gap-3 rounded-lg border border-border px-3 py-2">
            <Checkbox
              id="ai-decides-counts"
              checked={aiDecidesCounts}
              onCheckedChange={(v) => {
                const enabled = !!v;
                setAiDecidesCounts(enabled);

                if (!enabled) {
                  setMinimumPerTypeInput((prev) => {
                    const next = { ...prev };
                    selected.forEach((type) => {
                      const parsed = Number.parseInt(next[type], 10);
                      if (!Number.isFinite(parsed) || parsed <= 0) {
                        next[type] = "1";
                      }
                    });
                    return next;
                  });
                }
              }}
            />
            <Label
              htmlFor="ai-decides-counts"
              className="cursor-pointer font-normal"
            >
              Let AI decide question counts
            </Label>
          </div>

          <div className="flex items-center gap-3 rounded-lg border border-border px-3 py-2">
            <Checkbox
              id="require-sources"
              checked={requireSources}
              onCheckedChange={(v) => setRequireSources(!!v)}
            />
            <Label
              htmlFor="require-sources"
              className="cursor-pointer font-normal"
            >
              Ask AI to include source references in exam description
            </Label>
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="tpl-topic">
              Optional topic/context to include in AI prompt
            </Label>
            <Textarea
              id="tpl-topic"
              value={topicContext}
              onChange={(e) => setTopicContext(e.target.value)}
              rows={4}
              placeholder="Add your custom guidance, scope, constraints, or preferred style for this exam."
            />
          </div>

          {!aiDecidesTypes && (
            <QuestionTypeRules
              aiDecidesTypes={aiDecidesTypes}
              aiDecidesCounts={aiDecidesCounts}
              isTypeEnabled={isTypeEnabled}
              onSetTypeEnabled={setTypeEnabled}
              minimumPerTypeInput={minimumPerTypeInput}
              minimumPerType={minimumPerType}
              onSetMinimumInput={(type, raw) =>
                setMinimumPerTypeInput((prev) => ({
                  ...prev,
                  [type]: raw,
                }))
              }
              onEnableAll={() =>
                setSelected(
                  new Set<TemplateTypeSelection>([
                    "true_false",
                    "multiple_choice",
                    "identification_no_choices",
                    "identification_with_choices",
                    "matching",
                    "enumeration",
                  ]),
                )
              }
              onResetAll={() => {
                setSelected(new Set());
                setMinimumPerTypeInput({
                  true_false: "0",
                  multiple_choice: "0",
                  identification_no_choices: "0",
                  identification_with_choices: "0",
                  matching: "0",
                  enumeration: "0",
                });
              }}
            />
          )}

          {feedback && <p className="text-sm text-primary">{feedback}</p>}
        </div>

        <DialogFooter className="mx-0 flex-wrap border-t border-border px-4 py-4 sm:px-6">
          <Button variant="secondary" onClick={onClose}>
            Cancel
          </Button>
          <Button
            variant="secondary"
            leftIcon={
              jsonCopied ? (
                <Check className="h-4 w-4" />
              ) : (
                <Copy className="h-4 w-4" />
              )
            }
            onClick={() => void copyJson()}
          >
            {jsonCopied ? "Copied JSON" : "Copy JSON"}
          </Button>
          <Button
            leftIcon={
              promptCopied ? (
                <Check className="h-4 w-4" />
              ) : (
                <Bot className="h-4 w-4" />
              )
            }
            onClick={() => void copyAiPrompt()}
          >
            {promptCopied ? "Copied Prompt" : "Copy AI Prompt"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
