"use client";

import { Bot, Copy, FileJson } from "lucide-react";
import { useMemo, useState } from "react";

import {
  buildAiExamPrompt,
  generateTemplateExam,
  stringifyTemplateExam,
  type TemplateTypeMinimums,
  type TemplateTypeSelection,
} from "@/lib/template-generator";

import { Button } from "./Button";
import { Checkbox } from "./checkbox";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "./dialog";
import { Input } from "./input";
import { Label } from "./label";
import { Textarea } from "./textarea";

const TYPES: Array<{ key: TemplateTypeSelection; label: string }> = [
  { key: "true_false", label: "True/False" },
  { key: "multiple_choice", label: "Multiple Choice" },
  { key: "identification_no_choices", label: "Identification (No Choices)" },
  {
    key: "identification_with_choices",
    label: "Identification (With Choices)",
  },
  { key: "matching", label: "Matching" },
  { key: "enumeration", label: "Enumeration" },
];

interface TemplateGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function TemplateGeneratorModal({
  isOpen,
  onClose,
}: TemplateGeneratorModalProps) {
  const [selected, setSelected] = useState<Set<TemplateTypeSelection>>(
    new Set(["true_false", "multiple_choice"]),
  );
  const [aiDecides, setAiDecides] = useState(true);
  const [title, setTitle] = useState("Mockly Template Exam");
  const [description, setDescription] = useState(
    "Template generated by Mockly.",
  );
  const [subject, setSubject] = useState("General");
  const [passingScoreInput, setPassingScoreInput] = useState("70");
  const [requireSources, setRequireSources] = useState(true);
  const [topicContext, setTopicContext] = useState("");
  const [minimumPerTypeInput, setMinimumPerTypeInput] = useState<
    Record<TemplateTypeSelection, string>
  >({
    true_false: "0",
    multiple_choice: "0",
    identification_no_choices: "0",
    identification_with_choices: "0",
    matching: "0",
    enumeration: "0",
  });
  const [feedback, setFeedback] = useState<string | null>(null);

  const selectedArray = useMemo(() => Array.from(selected), [selected]);

  const clampInt = (
    raw: string,
    min: number,
    max: number,
    fallback: number,
  ) => {
    const parsed = Number.parseInt(raw, 10);
    if (!Number.isFinite(parsed)) return fallback;
    return Math.max(min, Math.min(max, parsed));
  };

  const passingScore = clampInt(passingScoreInput, 0, 100, 70);

  const isTypeEnabled = (type: TemplateTypeSelection) => selected.has(type);

  const setTypeEnabled = (type: TemplateTypeSelection, enabled: boolean) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (enabled) next.add(type);
      else next.delete(type);
      return next;
    });

    if (!enabled) {
      setMinimumPerTypeInput((prev) => ({ ...prev, [type]: "0" }));
    }
  };

  const minimumPerType: TemplateTypeMinimums = {
    true_false: clampInt(minimumPerTypeInput.true_false, 0, 200, 0),
    multiple_choice: clampInt(minimumPerTypeInput.multiple_choice, 0, 200, 0),
    identification_no_choices: clampInt(
      minimumPerTypeInput.identification_no_choices,
      0,
      200,
      0,
    ),
    identification_with_choices: clampInt(
      minimumPerTypeInput.identification_with_choices,
      0,
      200,
      0,
    ),
    matching: clampInt(minimumPerTypeInput.matching, 0, 200, 0),
    enumeration: clampInt(minimumPerTypeInput.enumeration, 0, 200, 0),
  };

  const generateExam = () =>
    generateTemplateExam(
      selectedArray,
      { title, description, passingScore, subject },
      { aiDecidesQuestionTypesAndCounts: aiDecides },
    );

  const copyJson = async () => {
    if (!aiDecides && selected.size === 0) {
      setFeedback("Select at least one question type.");
      return;
    }

    await navigator.clipboard.writeText(stringifyTemplateExam(generateExam()));
    setFeedback("Template copied to clipboard.");
  };

  const copyAiPrompt = async () => {
    if (!aiDecides && selected.size === 0) {
      setFeedback("Select at least one question type.");
      return;
    }

    const prompt = buildAiExamPrompt(generateExam(), {
      requireSources,
      allowNonJsonInput: true,
      topicContext,
      minQuestionCountPerType: minimumPerType,
    });
    await navigator.clipboard.writeText(prompt);
    setFeedback("AI prompt copied. Paste it in ChatGPT/Claude/Gemini.");
  };

  return (
    <Dialog
      open={isOpen}
      onOpenChange={(open) => {
        if (!open) onClose();
      }}
    >
      <DialogContent className="flex max-h-[92vh] w-full max-w-[calc(100%-2rem)] flex-col gap-0 overflow-hidden p-0 sm:max-w-3xl lg:max-w-4xl">
        <DialogHeader className="flex-row items-center gap-2 border-b border-border px-6 py-4">
          <FileJson className="h-5 w-5 text-primary" />
          <DialogTitle>Template Generator</DialogTitle>
        </DialogHeader>

        <div className="space-y-5 overflow-y-auto px-6 py-5">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <Label htmlFor="tpl-title">Exam Title</Label>
              <Input
                id="tpl-title"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="tpl-subject">Subject</Label>
              <Input
                id="tpl-subject"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
              />
            </div>

            <div className="space-y-1.5 sm:col-span-2">
              <Label htmlFor="tpl-desc">Description</Label>
              <Input
                id="tpl-desc"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
              />
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="tpl-pass">Passing Score (%)</Label>
              <Input
                id="tpl-pass"
                type="number"
                min={0}
                max={100}
                value={passingScoreInput}
                onChange={(e) => setPassingScoreInput(e.target.value)}
                onBlur={() => setPassingScoreInput(String(passingScore))}
              />
            </div>
          </div>

          <div className="flex items-center gap-3 rounded-lg border border-border px-3 py-2">
            <Checkbox
              id="ai-decides"
              checked={aiDecides}
              onCheckedChange={(v) => setAiDecides(!!v)}
            />
            <Label htmlFor="ai-decides" className="cursor-pointer font-normal">
              Let AI decide question types and question counts
            </Label>
          </div>

          <div className="flex items-center gap-3 rounded-lg border border-border px-3 py-2">
            <Checkbox
              id="require-sources"
              checked={requireSources}
              onCheckedChange={(v) => setRequireSources(!!v)}
            />
            <Label
              htmlFor="require-sources"
              className="cursor-pointer font-normal"
            >
              Ask AI to include source references in exam description
            </Label>
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="tpl-topic">
              Optional topic/context to include in AI prompt
            </Label>
            <Textarea
              id="tpl-topic"
              value={topicContext}
              onChange={(e) => setTopicContext(e.target.value)}
              rows={4}
              placeholder="Add your custom guidance, scope, constraints, or preferred style for this exam."
            />
          </div>

          <div>
            <div className="mb-2 flex flex-wrap items-start justify-between gap-3">
              <div>
                <p className="text-sm font-medium">Question Type Rules</p>
                <p className="text-xs text-muted-foreground">
                  Toggle types and optionally set per-type minimums in one
                  place.
                </p>
                <p className="mt-1 text-xs text-muted-foreground">
                  {aiDecides
                    ? "Enabled types are soft preferences; minimums are hard constraints if > 0."
                    : "Enable at least one type. Minimums are hard constraints if > 0."}
                </p>
              </div>
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setSelected(new Set(TYPES.map((t) => t.key)))}
                >
                  Enable all
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    setSelected(new Set());
                    setMinimumPerTypeInput({
                      true_false: "0",
                      multiple_choice: "0",
                      identification_no_choices: "0",
                      identification_with_choices: "0",
                      matching: "0",
                      enumeration: "0",
                    });
                  }}
                >
                  Reset
                </Button>
              </div>
            </div>

            <div className="grid gap-2 sm:grid-cols-2">
              {TYPES.map((item) => {
                const enabled = isTypeEnabled(item.key);
                return (
                  <div
                    key={item.key}
                    className="flex items-center justify-between gap-3 rounded-lg border border-border px-3 py-2 text-sm"
                  >
                    <div className="flex min-w-0 flex-1 items-center gap-2">
                      <Checkbox
                        id={`type-${item.key}`}
                        checked={enabled}
                        onCheckedChange={(v) => setTypeEnabled(item.key, !!v)}
                      />
                      <Label
                        htmlFor={`type-${item.key}`}
                        className="cursor-pointer truncate font-normal"
                      >
                        {item.label}
                      </Label>
                    </div>
                    <div className="flex items-center gap-2 text-xs text-muted-foreground">
                      <span>Min questions</span>
                      <Input
                        type="number"
                        min={0}
                        max={200}
                        value={minimumPerTypeInput[item.key]}
                        className="h-7 w-20 px-2 text-xs"
                        onChange={(e) => {
                          const raw = e.target.value;
                          setMinimumPerTypeInput((prev) => ({
                            ...prev,
                            [item.key]: raw,
                          }));
                          const parsed = Number.parseInt(raw, 10);
                          if (
                            Number.isFinite(parsed) &&
                            parsed > 0 &&
                            !enabled
                          ) {
                            setSelected((prev) => new Set(prev).add(item.key));
                          }
                        }}
                        onBlur={() =>
                          setMinimumPerTypeInput((prev) => ({
                            ...prev,
                            [item.key]: String(minimumPerType[item.key] ?? 0),
                          }))
                        }
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {feedback && <p className="text-sm text-primary">{feedback}</p>}
        </div>

        <DialogFooter className="border-t border-border px-6 py-4">
          <Button variant="secondary" onClick={onClose}>
            Cancel
          </Button>
          <Button
            variant="secondary"
            leftIcon={<Copy className="h-4 w-4" />}
            onClick={() => void copyJson()}
          >
            Copy JSON
          </Button>
          <Button
            leftIcon={<Bot className="h-4 w-4" />}
            onClick={() => void copyAiPrompt()}
          >
            Copy AI Prompt
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
